### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by websnap** [lightna-project/lightna#11]
**STR:**
Run command: composer lightna:build
**ER:**
Successful build.
**AR:**
Error:
`PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, null given in /lightna/code/lightna/magento-os-backend/App/Query/EavAbstract.php:69
Stack trace:
#0 /lightna/code/lightna/magento-os-backend/App/Query/EavAbstract.php(69): explode()
#1 /lightna/code/lightna/magento-os-backend/App/Query/EavAbstract.php(45): Lightna\Magento\App\Query\EavAbstract->processOptions()
#2 /lightna/code/lightna/magento-os-backend/Index/Product/BatchDataProvider.php(99): Lightna\Magento\App\Query\EavAbstract->getAttributeValues()
#3 /lightna/code/lightna/magento-os-backend/Index/Product/BatchDataProvider.php(44): Lightna\Magento\Index\Product\BatchDataProvider->loadAttributes()
#4 /lightna/code/lightna/magento-os-backend/Index/Product.php(44): Lightna\Magento\Index\Product\BatchDataProvider->getData()
#5 /lightna/code/lightna/lightna-engine/App/Index/IndexAbstract.php(13): Lightna\Magento\Index\Product->getBatchData()
#6 /lightna/code/lightna/lightna-engine/App/Indexer.php(37): Lightna\Engine\App\Index\IndexAbstract->refresh()
#7 /lightna/code/lightna/lightna-engine/App/Indexer.php(29): Lightna\Engine\App\Indexer->refreshAll()
#8 /lightna/code/lightna/lightna-engine/App/Console/Deploy/Data.php(24): Lightna\Engine\App\Indexer->reindex()
#9 /lightna/code/lightna/lightna-engine/App/Cli.php(18): Lightna\Engine\App\Console\Deploy\Data->run()
#10 /lightna/code/lightna/lightna-engine/cli(29): Lightna\Engine\App\Cli->run()
#11 /lightna/entry/magento-os/cli(8): require('...')
#12 {main}
  thrown in /lightna/code/lightna/magento-os-backend/App/Query/EavAbstract.php on line 69`

**Comment by vesan-83** [comment]
seems you have some multiselect attribute NULL. needs to be quick fixed by simple (string) before explode

**Comment by vesan-83** [comment]
please check if it works now
